### ISSUE TITLE
Ruby 2.2.1 crashes trying to get screen size on Windows

### ISSUE THREAD

**Issue by Azolo** [ConnorAtherton/rb-readline#119]
Some changes in Ruby 2.2 must have caused some changes in how the buffer size was looked up.

In essence with RubyInstaller 2.2.1 when trying to launch with console io we get:

    PS C:\Users\Justin> irb
    C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:1866:in ``': No such file or directory - stty size (Errno::ENOENT)
            from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:1866:in `block in _rl_get_screen_size'
            from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:6902:in `retry_if_interrupted'
            from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:1865:in `_rl_get_screen_size'
            from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:1992:in `_rl_init_terminal_io'
            from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:2508:in `readline_initialize_everything'
            from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:3793:in `rl_initialize'
            from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:4813:in `readline'
            from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/readline.rb:40:in `readline'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/input-method.rb:150:in `gets'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:469:in `block (2 levels) in eval_input'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:623:in `signal_status'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:468:in `block in eval_input'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:188:in `call'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:188:in `buf_input'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:103:in `getc'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/slex.rb:205:in `match_io'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/slex.rb:75:in `match'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:282:in `token'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:264:in `lex'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:235:in `block (2 levels) in each_top_level_statement'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `loop'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `block in each_top_level_statement'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `catch'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `each_top_level_statement'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:485:in `eval_input'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:395:in `block in start'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:394:in `catch'
            from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:394:in `start'
            from C:/Ruby/Ruby221-x64/bin/irb:11:in `<main>'

The crash is obviously because Windows doesn't have a program named `stty`. But it seems like the root cause on why it's getting to the need to call `stty` is from something else entirely.

**Comment by phasis68** [comment]
Hi,


2015-03-06 13:45 GMT+09:00 Justin Baker <notifications@github.com>:

> Some changes in Ruby 2.2 must have caused some changes in how the buffer
> size was looked up.
>
> In essence with RubyInstaller 2.2.1 when trying to launch with console io
> we get:
>
> PS C:\Users\Justin> irb
> C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:1866:in ``': No such file or directory - stty size (Errno::ENOENT)
>         from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:1866:in `block in _rl_get_screen_size'
>         from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:6902:in `retry_if_interrupted'
>         from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:1865:in `_rl_get_screen_size'
>         from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:1992:in `_rl_init_terminal_io'
>         from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:2508:in `readline_initialize_everything'
>         from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:3793:in `rl_initialize'
>         from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:4813:in `readline'
>         from C:/Ruby/Ruby221-x64/lib/ruby/site_ruby/2.2.0/readline.rb:40:in `readline'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/input-method.rb:150:in `gets'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:469:in `block (2 levels) in eval_input'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:623:in `signal_status'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:468:in `block in eval_input'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:188:in `call'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:188:in `buf_input'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:103:in `getc'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/slex.rb:205:in `match_io'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/slex.rb:75:in `match'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:282:in `token'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:264:in `lex'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:235:in `block (2 levels) in each_top_level_statement'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `loop'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `block in each_top_level_statement'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `catch'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `each_top_level_statement'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:485:in `eval_input'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:395:in `block in start'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:394:in `catch'
>         from C:/Ruby/Ruby221-x64/lib/ruby/2.2.0/irb.rb:394:in `start'
>         from C:/Ruby/Ruby221-x64/bin/irb:11:in `<main>'
>
> The crash is obviously because Windows doesn't have a program named stty.
> But it seems like the root cause on why it's getting to the need to call
> stty is from something else entirely.
>
> ​Obviously Windows doesn't have a program named stty.​ But it is not a
root cause.
The root cause is require 'dl' of line no 4369 in rbreadline.rb

The current ConnorAtherton/rb-readline fixed the issue.
You just need copy ConnorAtherton/rb-readline to rubyinstaller packgage.

You can trust me, I am an author of rb-readline.

​Regards,
Park Heesob​

**Comment by Azolo** [comment]
Alright, cool. I'll try building against master.

Thanks for your promptness.

If all goes well, is there any chance I could get you to do another release for me?

**Comment by Azolo** [comment]
I just wanted to say thank you again.

You saved me a lot of stress. :relieved:
