### ISSUE TITLE
new release 

### ISSUE THREAD

**Issue by langalex** [ConnorAtherton/rb-readline#132]
can we get a new release please that includes 1d4e43c8bd28726596ae40eab7d0e2820a0f0183?

**Comment by chulkilee** [comment]
0.5.4 is available as a github release, but it's not pushed to rubygems.org :(

**Comment by maryamklabib** [comment]
Could this get released on RubyGems?

We love your gem sooo much but the error makes us sooo sad

#publishyourgembro

**Comment by pattyde** [comment]
@maryamklabib I edited my Gemfile to the following:

`gem "rb-readline", git: "git@github.com:ConnorAtherton/rb-readline.git", branch: "master"` 

This allowed me to install v0.5.4 and get rid of the console warnings.

**Comment by ConnorAtherton** [comment]
Hey all, sorry for the delay. 

https://rubygems.org/gems/rb-readline/versions/0.5.4
