### ISSUE TITLE
Add support for Readline.vi_editing_mode? & Readline.emacs_editing_mode?

### ISSUE THREAD

**Issue by kyrylo** [ConnorAtherton/rb-readline#152]
The Readline bundled with Ruby supports these methods:

* https://ruby-doc.org/stdlib-2.1.1/libdoc/readline/rdoc/Readline.html#method-c-emacs_editing_mode-3F
* https://ruby-doc.org/stdlib-2.1.1/libdoc/readline/rdoc/Readline.html#method-c-vi_editing_mode-3F

In Pry we now have some logic that works only when `vi_editing_mode` is enabled. However, it's incompatible with rb-readline because we don't seem to be able to check which mode is currently on.

**Comment by Spakman** [comment]
Thanks for reporting this! These methods have been implemented in https://github.com/ConnorAtherton/rb-readline/commit/f1965a9b3847914f8841de3162d33e1cafe3ffbb.
